### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by BooBSD** [lambdalisue/django-thumbnailfield#4]
Hello,
How can I change quality of saved images? As I understood, by default quality is 75%.
Thank you.

**Comment by lambdalisue** [comment]
Hum... currently django-thumbnailfield does not support it but I think it should be configurable.
I'll check and add that feature soon.

**Comment by BooBSD** [comment]
Thank you.

**Comment by lambdalisue** [comment]
Could you try the HEAD version? If it works, I'll update the version on PyPI.

```sh
pip install git+https://github.com/lambdalisue/django-thumbnailfield
```

You can specify keyword arguments as `pil_save_options` like

```python
thumbnail = ThumbnailField(_('thumbnail'), upload_to='img/thumbnails', null=True, blank=True,
        pil_save_options={
            # Options of PIL Image.save() method.
            # e.g. quality control
            'quality': 100,
        },
        patterns={
            # Pattern Format:
        }
)
```

**Comment by BooBSD** [comment]
Yes, it works. But maybe better will be used THUMBNAILFIELD_QUALITY in Django settings?

**Comment by lambdalisue** [comment]
> But maybe better will be used THUMBNAILFIELD_QUALITY in Django settings?

Well, I thought so but then you will lose the possibility to control other options listed in http://pillow.readthedocs.org/en/latest/handbook/image-file-formats.html
That's why I didn't prepare a special setting just for quality.

**Comment by BooBSD** [comment]
Ok. Thanks!

**Comment by lambdalisue** [comment]
Ok. I updated the PyPI version. Now you can install the v0.2.5 which contains the settings above via `pip install django-thumbnailfield`

**Comment by BooBSD** [comment]
Thank you!

2015-01-18 16:58 GMT+02:00 Λlisue <notifications@github.com>:

> Ok. I updated the PyPI version. Now you can install the v0.2.5 which
> contains the settings above via pip install django-thumbnailfield
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lambdalisue/django-thumbnailfield/issues/4#issuecomment-70411205>
> .
>



-- 
Best regards,
Artem.
