### ISSUE TITLE
Image files not deleted

### ISSUE THREAD

**Issue by BooBSD** [lambdalisue/django-thumbnailfield#5]
It seems, that after deleting an object, image files (thumbnail and original) are staying untouched.
Though, I suppose these files should be also deleted with DB object.
How can I delete these files along with deleting an object from DB?
Thank you.

My settings:

```
THUMBNAILFIELD_REMOVE_PREVIOUS = True
THUMBNAILFIELD_DEFAULT_PIL_SAVE_OPTIONS = {'quality': 95}
```
And my model field:
```
image = ThumbnailField(u'Photo', upload_to='farm/%Y/%m/%d', patterns={
    't': (128, 128, thumb_and_crop),
})
```

**Comment by lambdalisue** [comment]
Hum... It sounds a bug. I'm busy in this and next week so I'll check it out 3rd week of Feb.

**Comment by BooBSD** [comment]
Thanks!

2015-02-03 4:20 GMT+02:00 Λlisue <notifications@github.com>:

> Hum... It sounds a bug. I'm busy in this and next week so I'll check it
> out 3rd week of Feb.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lambdalisue/django-thumbnailfield/issues/5#issuecomment-72580430>
> .
>



-- 
Best regards,
Artem.

**Comment by lambdalisue** [comment]
Hi. I didn't know that but it seems a correct behavior for file field.
http://stackoverflow.com/questions/16041232/django-delete-filefield
